//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monambike.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SocialMediaLinks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SocialMediaLinks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monambike.Web.Resources.SocialMediaLinks", typeof(SocialMediaLinks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/monambike.
        /// </summary>
        internal static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.instagram.com/monambike/.
        /// </summary>
        internal static string InstagramMonambike {
            get {
                return ResourceManager.GetString("InstagramMonambike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.instagram.com/monambike_portfolio/.
        /// </summary>
        internal static string InstagramMonambikePortfolio {
            get {
                return ResourceManager.GetString("InstagramMonambikePortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://monambike.itch.io/.
        /// </summary>
        internal static string ItchIo {
            get {
                return ResourceManager.GetString("ItchIo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.linkedin.com/in/monambike.
        /// </summary>
        internal static string Linkedin {
            get {
                return ResourceManager.GetString("Linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://open.spotify.com/user/21jrwvbuag67jrte2nzmplhsy.
        /// </summary>
        internal static string Spotify {
            get {
                return ResourceManager.GetString("Spotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://steamcommunity.com/id/monambike.
        /// </summary>
        internal static string Steam {
            get {
                return ResourceManager.GetString("Steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tiktok.com/monambike.
        /// </summary>
        internal static string TikTok {
            get {
                return ResourceManager.GetString("TikTok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/Monambike.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/user/monambike.
        /// </summary>
        internal static string YoutubeMonambike {
            get {
                return ResourceManager.GetString("YoutubeMonambike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/@monambike_portfolio.
        /// </summary>
        internal static string YoutubeMonambikePortfolio {
            get {
                return ResourceManager.GetString("YoutubeMonambikePortfolio", resourceCulture);
            }
        }
    }
}
