name: Publish .NET 8 Blazor Wasm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_PACKAGES_TOKEN: ${{ secrets.GIT_PACKAGES_TOKEN }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Monambike.Website.sln
          
      - name: Build and publish
        run: dotnet publish src/Monambike.Website.sln -c Release -f net8.0 -r browser-wasm --self-contained --output ./publish-folder

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish-folder/
          server-dir: public_html/
          passive: true
