name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Clear NuGet sources
        run: dotnet nuget remove source nuget.org || true
  
      - name: Authenticate to GitHub Packages
        run: | 
          dotnet nuget remove source github || true
          dotnet nuget add source "https://nuget.pkg.github.com/monambike/index.json"" \
            --name github \
            --username monambike \
            --password "${{ secrets.GIT_PACKAGES_TOKEN }}" \
            --store-password-in-clear-text

      - name: Publish
        run: dotnet publish src/Monambike.Web/Monambike.Web.csproj -c Release -o release

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
